name: daily puzzle deployment

on:
  schedule:
    - cron:  '00 5 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: amondnet/vercel-action@v25
        with:
          node-version: '20'
          vercel-token: ${{ secrets.ZEIT_TOKEN }}
          vercel-org-id: ${{ secrets.ZEIT_ORG_ID }}
          vercel-project-id: ${{ secrets.ZEIT_PROJECT_ID }}
          vercel-args: '--prod'
